my_job.port=7070
#my_job.path=/abc
#my_job.db.type=mysql
my_job.db.url=192.168.33.10:3306
my_job.db.schema=wx_xxl_job
# mysql url?????
my_job.db.url-ops=?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
my_job.db.username=root
my_job.db.password=root
my_job.db.driver-class-name=com.mysql.cj.jdbc.Driver

my_job.mail.host=
my_job.mail.port=
my_job.mail.username=
my_job.mail.password=
my_job.mail.from=

my_job.token=local-sample
